var melodies = {
    house1: {
        bpmMult: 1,
        instrumentEl: 'Monosynth',
        presetEl: 'bass',
        delayEl: 0.7,
        reverbEl: 0.8,
        stepsObj: { "1": "..x...x.........", "2": "x...x...........", "7": "............x.x.", "8": "..........x....." },
    },
    bellaCiao: {
        bpmMult: 0.5,
        instrumentEl: 'Monosynth',
        presetEl: 'shinybass2',
        stepsObj: { "4": "x.....x.........x.....x.........", "6": "..x...............x.............", "7": "....x...............x...........", "-1": "..............x................." },
    },
    canYouFeelIt: {
        bpmMult: 0.5,
        instrumentEl: 'Monosynth',
        presetEl: 'shinybass',
        delayEl: 0.7,
        reverbEl: 0.8,
        stepsObj: { "4": "......x.....x...", "9": ".........x...x..", "-3": "..x........x...." },
    },
    acid1: {
        bpmMult: 0.5,
        instrumentEl: 'PolySynth',
        presetEl: 'acidBass',
        delayEl: 0.5,
        delayTimeEl: 1 / 4,
        reverbEl: 0.8,
        stepsObj: { "4": "......x.....x...", "9": ".........x...x..", "-3": "..x........x...." },
    },
    ebHarMin: {
        bpmMult: 0.5,
        instrumentEl: 'PolyMono',
        presetEl: 'arpy',
        delayEl: 0.9,
        delayTimeEl: 1 / 4,
        reverbEl: 0.2,
        stepsObj: { "3": "x............x..", "5": ".x.........x....", "6": "..x.......x.....", "8": "...x.....x......", "10": "....x...x.......", "11": ".....x.x........", "14": "......x........." },
    },
    aMaj: {
        bpmMult: 1,
        instrumentEl: 'PolyMono',
        presetEl: 'warble',
        delayEl: 0.5,
        delayTimeEl: 1 / 4,
        reverbEl: 0.8,
        stepsObj: { "1": "....x...........", "2": "......x.........", "4": "........x.......", "6": "..........x.....", "8": "............x...", "-3": "x...............", "-1": "..x............." },
    },
    dMajArp: {
        bpmMult: 1,
        instrumentEl: 'PolyMono',
        presetEl: 'short.dry',
        delayEl: 0.5,
        delayTimeEl: 1 / 3,
        reverbEl: 0,
        stepsObj: { "0": ".........x..x...", "1": "...........x....", "-10": "x...............", "-8": "..x.............", "-7": ".x..x...........", "-5": "...x..x.........", "-4": ".....x..........", "-3": "........x......x", "-2": ".......x......x.", "-1": "..........x..x.." },
    },
    bNatMinArp: {
        bpmMult: 1,
        instrumentEl: 'PolyMono',
        presetEl: 'shinybass',
        delayEl: 0.5,
        delayTimeEl: 1 / 3,
        reverbEl: 0,
        stepsObj: { "-13": "x.......x.......", "-11": ".x.......x......", "-10": "..x.......x.....", "-8": "...x.......x....", "-6": "....x.......x...", "-5": ".....x.......x..", "-3": "......x.......x.", "-1": ".......x.......x" },
    },
    gMelMinArp: {
        bpmMult: 1,
        instrumentEl: 'FM',
        presetEl: '',
        delayEl: 0.2,
        delayTimeEl: 1 / 3,
        reverbEl: 0,
        stepsObj: { "-17": "x...............", "-15": "..x.............", "-14": "....x...........", "-12": "......x.........", "-10": "........x.......", "-8": "..........x.....", "-6": "............x...", "-5": "..............x." },
    }
};
